### ISSUE TITLE
Set up R CMD check using Github actions

### ISSUE THREAD

**Issue by kapsner** [mayer79/splitTools#17]
@mayer79 I was wondering, if you would be interested in setting up Github actions for this repo in order to run R CMD check on different systems (windows, linux, macOS) on a regular basis to see if the package / the version on github still builds on R-devel, for example.

I am using this for my R packages and found it very useful, also for checking PRs.

I have set up a branch in my fork introducing this CI-pipeline (you can have a look at the results [here](https://github.com/kapsner/splitTools/actions/runs/3122222811)). So if you like, I can open a PR - just let me know!

**Comment by mayer79** [comment]
Wow that's awesome! Do I need special prerequisites? If you open a PR, is there something I need to do to test the pipeline?

**Comment by kapsner** [comment]
> Do I need special prerequisites?

It might be that you need to activate "Actions" in the project settings. However, when the config-files are then found in the repo, the will be automatically triggerd according to the specifications.

Here are more general information: https://docs.github.com/en/actions

As of now, they are free for public repos (https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

> If you open a PR, is there something I need to do to test the pipeline?

I use the [`tic`](https://github.com/ropensci/tic) R package for setting up actions. Once, the config-files are present in the repo, you can run, for example, `tic::run_all_stages()` to test the pipeline locally.

**Comment by mayer79** [comment]
Implemented in https://github.com/mayer79/splitTools/pull/18, many thanks! When I find a bit of spare time, I need to study this stuff in more detail and consider adding it to my other packages as well.

**Comment by kapsner** [comment]
> ... and consider adding it to my other packages as well.

Just wanted to add that this should basically work with simply copy-pasting the .github-directory to the new repo together with the /.tic.R file. So there are no package-specifics hardcoded in the workflow files.

**Comment by mayer79** [comment]
That is what I had hoped. Perfect!
